name:                linear-haskell
version:             0.1.0.0
github:              "matsubara0507/linear-haskell"
license:             BSD-3-Clause
author:              "MATSUBARA Nobutada"
maintainer:          "nobutada0507@gmail.com"
copyright:           "2023 MATSUBARA Nobutada"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/matsubara0507/linear-haskell#readme>

dependencies:
- base >= 4.7 && < 5
- linear-base

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  linear-haskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - linear-haskell

tests:
  linear-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - linear-haskell
